services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\HRPayPalModule\:
      resource: 'src/*'
      exclude: 'src/**/{Exception,Shop}'
      public: true

  OxidEsales\PayPalModule\Core\Config:
      class: OxidEsales\PayPalModule\Core\Config
      public: true